import { useEffect, useState } from 'react';
import { ChevronRight, FileCode2, Folder, FolderOpen } from 'lucide-react';
import type { FileEntry } from '../../../packages/contracts';
import { bridge } from './bridge';
export function FileTree({ projectId, relative = '', depth = 0, selected, context, toggle, open, error, revision, selectable = true }: { projectId: string; relative?: string; depth?: number; selected: string; context: string[]; toggle: (p: string) => void; open: (p: string) => void; error: (e: unknown) => void; revision: number; selectable?: boolean }) {
  const [entries, setEntries] = useState<FileEntry[]>([]); const [expanded, setExpanded] = useState<string[]>([]);
  useEffect(() => { let alive = true; void bridge.tree(projectId, relative).then(e => { if (alive) setEntries(e); }).catch(error); return () => { alive = false; }; }, [projectId, relative, revision]);
  return <div>{entries.map(entry => <div key={entry.path}><div className={`tree-row ${selected === entry.path ? 'selected' : ''}`} style={{ paddingLeft: 12 + depth * 13 }}><button className="tree-label" title={entry.path} onClick={() => entry.directory ? setExpanded(prev => prev.includes(entry.path) ? prev.filter(p => p !== entry.path) : [...prev, entry.path]) : open(entry.path)}>{entry.directory ? <><ChevronRight size={12} className={expanded.includes(entry.path) ? 'rotated' : ''}/>{expanded.includes(entry.path) ? <FolderOpen size={15}/> : <Folder size={15}/>}</> : <FileCode2 size={15} className="file-icon"/>}<span>{entry.name}</span></button>{selectable && !entry.directory && <input aria-label={`将 ${entry.name} 加入上下文`} title="加入本轮上下文" type="checkbox" checked={context.includes(entry.path)} onChange={() => toggle(entry.path)}/>}</div>{entry.directory && expanded.includes(entry.path) && <FileTree {...{ projectId, selected, context, toggle, open, error, revision, selectable }} relative={entry.path} depth={depth + 1}/>}</div>)}</div>;
}
