import { _electron as electron } from 'playwright';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import assert from 'node:assert/strict';
import path from 'node:path';
import { createServer } from 'node:http';
import { checkPanelToggles } from './panel-checks.mjs';
const root = process.cwd();
const runDir = path.join(root, '.cache', `desktop-smoke-${Date.now()}`);
const project = path.join(runDir, 'sample-project'); await mkdir(project, { recursive: true });
const before = 'export const greeting = "Hello, LP Studio";\n';
await writeFile(path.join(project, 'greeting.ts'), before); await writeFile(path.join(project, 'README.md'), '# Sample project\n');
const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
const app = await electron.launch({ args: [path.join(root, 'dist/main/main.cjs')], cwd: runDir, env });
const errors = [];
const modelReply = '已检查 `greeting.ts`，这是待审核的修改。\n```lp-edit\n' + JSON.stringify({ path: 'greeting.ts', content: 'export const greeting = "AI reviewed change";\n' }) + '\n```';
let finishReply;
const replyGate = new Promise(resolve => { finishReply = resolve; });
const server = createServer(async (req, res) => {
  for await (const _ of req) { /* consume */ }
  res.writeHead(200, { 'Content-Type': 'text/event-stream' });
  res.write('data: ' + JSON.stringify({ choices: [{ delta: { content: modelReply.slice(0, 15) } }] }) + '\n\n');
  await replyGate;
  if (res.destroyed) return;
  res.end('data: ' + JSON.stringify({ choices: [{ delta: { content: modelReply.slice(15) } }] }) + '\n\ndata: [DONE]\n\n');
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const apiUrl = `http://127.0.0.1:${server.address().port}/v1`;
try {
  const page = await app.firstWindow(); page.on('pageerror', err => errors.push(err.message));
  await page.getByRole('heading', { name: '从想法，到下一次提交。' }).waitFor();
  // Exercise the themed UI confirmation rather than replacing native message boxes.
  await page.exposeFunction('acceptSmokeConfirmation', async () => { await page.locator('.confirmation-dialog[open]').getByRole('button', { name: '确认', exact: true }).click(); });
  await page.addInitScript(() => { window.addEventListener('DOMContentLoaded', () => window.studio.onConfirm(() => { void window.acceptSmokeConfirmation(); })); });
  await page.evaluate(() => window.studio.onConfirm(() => { void window.acceptSmokeConfirmation(); }));
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined');
  await app.evaluate(({ dialog }, project) => {
    dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [project] });

  }, project);
  await page.getByRole('button', { name: '打开本地项目' }).click();
  await page.getByRole('button', { name: 'greeting.ts', exact: true }).click();
  await page.locator('.monaco-editor').first().waitFor();
  await page.getByRole('checkbox', { name: '将 greeting.ts 加入上下文' }).check();
  const state = await page.evaluate(() => window.studio.bootstrap()); const projectId = state.projects[0].id;
  const session = await page.evaluate(({ projectId, providerId }) => window.studio.createSession(projectId, providerId), { projectId, providerId: state.providers[0].id });
  const result = await page.evaluate(async ({ projectId, sessionId }) => {
    const snap = await window.studio.readFile(projectId, 'greeting.ts');
    const change = await window.studio.propose(projectId, snap, 'export const greeting = "Reviewed change";\n');
    await window.studio.apply(change.id);
    const applied = await window.studio.readFile(projectId, 'greeting.ts');
    await window.studio.rollback(change.id);
    const restored = await window.studio.readFile(projectId, 'greeting.ts');
    const events = []; const stop = window.studio.onEvent(e => events.push(e));
    await window.studio.command(sessionId, 'Write-Output "DESKTOP_SMOKE_OK"');
    await new Promise((resolve, reject) => { const start = Date.now(); const poll = setInterval(() => { if (events.some(e => e.type === 'done')) { clearInterval(poll); resolve(); } else if (Date.now() - start > 15000) { clearInterval(poll); reject(Error('command timeout')); } }, 30); });
    stop(); return { applied: applied.content, restored: restored.content, events };
  }, { projectId, sessionId: session.id });
  assert.match(result.applied, /Reviewed change/); assert.equal(result.restored, before);
  assert.ok(result.events.some(e => e.text.includes('DESKTOP_SMOKE_OK'))); assert.ok(!result.events.some(e => e.type === 'error'));
  const secretId = randomUUID(); const secret = 'smoke-secret-never-store-plaintext';
  await page.evaluate(({ id, secret, apiUrl }) => window.studio.saveProvider({ id, name: 'Test API', kind: 'openai-api', model: 'test', executable: '', baseUrl: apiUrl, timeoutMs: 10000 }, secret), { id: secretId, secret, apiUrl });
  const secretFile = await readFile(path.join(runDir, '.lp-data', 'secrets.json'), 'utf8'); assert.ok(!secretFile.includes(secret));
  await page.reload();
  await page.getByRole('button', { name: 'greeting.ts', exact: true }).click(); await page.locator('.monaco-editor').first().waitFor();
  await checkPanelToggles(page);
  const commandProvider = state.providers.find(p => p.kind === 'command-cli');
  assert.ok(commandProvider, 'Command CLI seeded into a new workspace');
  const nav = name => page.locator('.rail').getByRole('button', { name, exact: true });
  await page.getByRole('textbox', { name: '对话输入' }).fill('保留的对话草稿');
  await nav('终端命令').click();
  await page.getByRole('textbox', { name: '终端命令', exact: true }).fill('Write-Output "draft"');
  await nav('模型与 API Key').click();
  await page.getByRole('heading', { name: '模型与连接' }).waitFor();
  assert.equal(await page.locator('.modal-backdrop, [role="dialog"]').count(), 0);
  assert.equal(await page.locator('.terminal-panel').isVisible(), false);
  assert.equal(await page.locator('.central-workspace .models-page').isVisible(), true);
  assert.equal(await page.locator('.project-panel').isVisible(), true);
  assert.equal(await page.locator('.preview-panel').isVisible(), true);
  assert.equal(await nav('模型与 API Key').getAttribute('aria-pressed'), 'true');
  const modelName = page.getByRole('textbox', { name: '连接名称', exact: true });
  await modelName.fill('未保存的模型草稿');
  await nav('设置').click();
  await page.getByRole('heading', { name: '工作台设置' }).waitFor();
  assert.equal(await page.locator('.models-page').isVisible(), false);
  assert.equal(await page.locator('.workspace-view:not([hidden])').evaluate(el => getComputedStyle(el).animationName), 'workspace-enter');
  await page.getByRole('button', { name: '工业浅色主题', exact: true }).click();
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'industrial');
  assert.equal(await page.locator('.project-panel').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(237, 240, 233)');
  await page.locator('.monaco-editor.vs').first().waitFor();
  await nav('工作台').click(); await checkPanelToggles(page);
  await nav('模型与 API Key').click(); assert.equal(await modelName.inputValue(), '未保存的模型草稿');
  // Narrow center columns must scroll vertically, without hiding form controls horizontally.
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1100, 760));
  await page.waitForFunction(() => window.innerWidth <= 1100);
  assert.equal(await page.locator('.page-scroll:not([hidden])').evaluate(el => el.scrollWidth <= el.clientWidth + 1), true);
  await page.getByRole('button', { name: '保存连接', exact: true }).scrollIntoViewIfNeeded();
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1520, 960));
  await nav('会话').click(); await page.getByRole('heading', { name: '会话', exact: true }).waitFor();
  await page.getByRole('textbox', { name: '搜索会话' }).fill('不存在的会话');
  await page.getByRole('heading', { name: '没有匹配的会话' }).waitFor();
  await page.getByRole('textbox', { name: '搜索会话' }).fill('');
  assert.equal(await page.locator('.session-card').count(), 1);
  await nav('终端命令').click(); assert.equal(await page.getByRole('textbox', { name: '终端命令', exact: true }).inputValue(), 'Write-Output "draft"');
  await nav('工作台').click(); assert.equal(await page.getByRole('textbox', { name: '对话输入' }).inputValue(), '保留的对话草稿');
  await nav('设置').click(); await page.keyboard.press('Control+l');
  assert.equal(await page.getByRole('textbox', { name: '对话输入' }).evaluate(el => el === document.activeElement), true);
  await page.reload(); await nav('设置').click();
  assert.equal(await page.getByRole('button', { name: '工业浅色主题', exact: true }).getAttribute('aria-pressed'), 'true');
  await page.emulateMedia({ reducedMotion: 'reduce' }); await nav('模型与 API Key').click();
  assert.equal(await page.locator('.workspace-view:not([hidden])').evaluate(el => getComputedStyle(el).animationName), 'none');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await nav('工作台').click();
  await page.getByRole('combobox', { name: '会话 CLI' }).selectOption(secretId);
  await page.getByRole('checkbox', { name: '将 greeting.ts 加入上下文' }).check();
  await page.getByRole('textbox', { name: '对话输入' }).fill('请检查 greeting.ts 并提出修改。');
  await page.getByRole('button', { name: '运行 · Ctrl+Enter' }).click();
  await page.getByRole('button', { name: '停止', exact: true }).waitFor();
  await nav('会话').click(); await page.locator('.session-running').waitFor();
  await nav('模型与 API Key').click();
  finishReply();
  await page.waitForFunction(async () => (await window.studio.bootstrap()).changes.some(c => c.state === 'pending'));
  await nav('会话').click();
  await page.locator('.session-card').first().click();
  await page.getByRole('textbox', { name: '对话输入' }).waitFor();
  await page.getByRole('button', { name: /greeting.ts 审核 diff/ }).waitFor({ timeout: 15000 });
  assert.ok(await page.locator('.message.assistant').innerText().then(t => t.includes('待审核的修改')));
  const afterRun = await page.evaluate(() => window.studio.bootstrap());
  assert.ok(afterRun.changes.some(c => c.state === 'pending' && c.after.includes('AI reviewed')));
  assert.equal(await readFile(path.join(project, 'greeting.ts'), 'utf8'), before);
  await page.getByRole('button', { name: /greeting.ts 审核 diff/ }).click();
  await page.locator('.monaco-diff-editor').waitFor();
  await mkdir(path.join(root, 'docs'), { recursive: true });
  await page.screenshot({ animations: 'disabled', path: path.join(root, 'docs', 'theme-industrial.png') });
  await nav('设置').click();
  await page.screenshot({ animations: 'disabled', path: path.join(root, 'docs', 'theme-settings.png') });
  await page.getByRole('button', { name: '午夜深蓝主题', exact: true }).click();
  await page.locator('.monaco-editor.vs-dark').first().waitFor();
  await nav('工作台').click();
  await page.screenshot({ animations: 'disabled', path: path.join(root, 'docs', 'desktop-preview.png') });
  // Exercise the new adapter through desktop IPC, without calling a paid account.
  const commandFixture = path.join(runDir, 'cmdc-fixture.mjs');
  await writeFile(commandFixture, `import assert from 'node:assert/strict';
const args = process.argv.slice(2);
if (args.includes('--version')) { console.log('cmdc fixture 1.0'); process.exit(0); }
if (args.includes('--list-models')) { console.log('Available models\\nfixture/model-a    reasoning\\nfixture/model-b    fast'); process.exit(0); }
assert.equal(args[args.indexOf('--model') + 1], 'fixture/model-b');
assert.equal(args[args.indexOf('--permission-mode') + 1], 'plan');
assert.equal(args[args.indexOf('--output-format') + 1], 'json');
process.stdin.setEncoding('utf8'); let input = ''; for await (const c of process.stdin) input += c;
assert.ok(input.includes('检查 cmdc 接入')); assert.ok(input.includes('greeting.ts'));
const text = 'COMMAND_CLI_DESKTOP_OK';
console.log(JSON.stringify({ type: 'event', event: { type: 'text_delta', delta: text } }));
console.log(JSON.stringify({ type: 'result', subtype: 'success', finalText: text }));
`);
  await page.evaluate(({ config, executable }) => window.studio.saveProvider({ ...config, executable }), { config: commandProvider, executable: commandFixture });
  await page.reload();
  await nav('模型与 API Key').click();
  await page.locator('.model-item').filter({ hasText: 'Command CLI (cmdc)' }).click();
  assert.equal(await page.getByLabel(/^适配器/).inputValue(), 'command-cli');
  await page.getByRole('button', { name: '检测已保存连接', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.probe-result')?.textContent.includes('cmdc fixture 1.0'));
  await nav('工作台').click();
  await page.getByRole('combobox', { name: '会话 CLI' }).selectOption(commandProvider.id);
  await page.getByRole('button', { name: '读取 CLI 支持的模型', exact: true }).click();
  await page.getByRole('combobox', { name: '会话模型', exact: true }).selectOption('fixture/model-b');

  await page.getByRole('checkbox', { name: '将 greeting.ts 加入上下文' }).check();
  await page.getByRole('textbox', { name: '对话输入' }).fill('检查 cmdc 接入');
  await page.getByRole('button', { name: '运行 · Ctrl+Enter' }).click();
  await page.waitForFunction(async () => (await window.studio.bootstrap()).sessions.some(s => s.messages.some(m => m.role === 'assistant' && m.text === 'COMMAND_CLI_DESKTOP_OK')));
  await page.locator('.message.assistant .message-text').filter({ hasText: 'COMMAND_CLI_DESKTOP_OK' }).waitFor();
  assert.equal(await page.locator('.message.assistant .message-text').innerText(), 'COMMAND_CLI_DESKTOP_OK');
  assert.ok(await page.getByRole('combobox', { name: '会话 CLI', exact: true }).isDisabled());
  assert.ok(await page.getByRole('combobox', { name: '会话模型', exact: true }).isDisabled());
  assert.equal(await readFile(path.join(project, 'greeting.ts'), 'utf8'), before);
  assert.deepEqual(errors, []);
  console.log('Electron smoke passed: native window, isolated renderer, file tree, Monaco, context, apply/rollback, PowerShell, encrypted vault, shortcuts, embedded navigation, draft retention, background streaming, panel geometry and retained toggle, Command CLI integration, narrow layout, themes, persistence, reduced motion.');
} finally { finishReply(); server.closeAllConnections(); server.close(); await app.close(); }

// Window chrome and destructive session actions are part of desktop regression.
await import('./chrome-smoke.mjs');
